name: visionary
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  tflite: ^1.1.2
  image_picker: ^0.8.4+5
  camera: ^0.9.4+9
  flutter_svg: ^0.22.0

  cupertino_icons: ^1.0.2

  flutter_tts: ^3.3.3

  simple_ocr_plugin: ^0.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/models/object_detection/ssd_mobilenet.tflite
    - assets/models/object_detection/labels.txt
    - assets/models/
    - assets/images/
    
